site_name: DNAflexpy
site_url: https://upalabdhaD.github.io/dnaflexpy/
site_description: A python package to calculate DNA flexibility from DNA sequences
site_author: Upalabdha Dey

theme:
  name: material
  language: en  # Language code for syntax highlighting
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Toggle Light Mode
      primary: teal
      accent: lime

extra:
  content:
    code:
      annotation: true
      copy: true
  toc:
    integrate: true
    numbered: true

nav:
  - Home: index.md
  - Usage: usage.md
  - FAQ: faq.md
  - Installation: installation.md
  - Citation: citation.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

plugins:
  - search
#   - mkdocs-material
repo_url: https://github.com/upalabdhaD/dnaflexpy
repo_name: GitHub